import { BvAttendance, BvGroupMembers } from '@/lib/backend-sdk';

const refs = (value: unknown): string[] => Array.isArray(value)
  ? value.flatMap(refs)
  : value == null ? [] : [String(value).trim()].filter(Boolean);

/** Read a resolved member's saved marks, including attendance from former groups. */
export async function readBvProfileAttendance(identities: string[], sinceDate: string, untilDate?: string) {
  const aliases = new Set(identities.flatMap(refs));
  const keys = new Set([...aliases].map(value => value.toLowerCase()));
  const { records: memberships } = await BvGroupMembers.findAll({
    fields: ['id', 'user', 'userId', 'memberId'], limit: 5000,
  });
  for (const membership of memberships) {
    const references = refs([membership.id, membership.user, membership.userId, membership.memberId]);
    if (references.some(value => keys.has(value.toLowerCase()))) {
      references.forEach(value => aliases.add(value));
    }
  }

  // Equality/in reads need no composite date index. Include single-value
  // relation arrays from legacy records; filter dates after the scoped read.
  const ownerValues = [...new Set([...aliases, ...[...aliases].map(value => value.toLowerCase())])]
    .flatMap(value => [value, [value]]);
  const byDate = new Map<string, boolean>();
  for (let i = 0; i < ownerValues.length; i += 30) {
    let offset = 0;
    while (true) {
      const { records, hasMore } = await BvAttendance.findAll({
        filters: { user: { in: ownerValues.slice(i, i + 30) } },
        fields: ['id', 'attendanceDate', 'present', 'group', 'groupId'],
        limit: 1000, offset,
      });
      for (const record of records) {
        const date = String(record.attendanceDate || '').slice(0, 10);
        // Group-less rows were generated by Sadhana and are not official marks.
        if (!refs([record.group, record.groupId]).length || !date || date < sinceDate || (untilDate && date > untilDate)) continue;
        byDate.set(date, byDate.get(date) === true || record.present === true);
      }
      if (!hasMore) break;
      offset += 1000;
    }
  }
  return [...byDate].map(([attendanceDate, present]) => ({
    attendanceDate, present, status: present ? 'P' : 'A', sessionTopic: '',
  })).sort((a, b) => b.attendanceDate.localeCompare(a.attendanceDate));
}
